apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
    path('', views.Home_Noticias, name="h_noticias"),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path,include #importo la funcion include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.Home, name = 'inicio'),

    path('pruebas/', views.Pruebas, name="pruebas"),

    path('contacto/', views.contacto, name = 'contacto'),
    
    #APP NOTICIAS
    path('noticias/', include('apps.noticias.urls')),
]

apps/noticias/models.py
from django.db import models

class Noticia(models.Model):
    creado = models.DateTimeField('creado', auto_now_add=True)
    modificado = models.DateTimeField('modificado', auto_now=True)

    titulo = models.CharField(max_length=250)
    contenido = models.TextField()

    def __str__(self):
        return self.titulo

apps/noticias/views.py
from django.shortcuts import render

# Create your views here.

def Home_Noticias(request):
    
    return render(request, 'noticias/home_noticias.html')

proyecto/views.py
from django.shortcuts import render

def Home(request):

    return render(request, 'home.html')


def Pruebas(request):
                                # este def es de andres jugando un poco nomas
    return render(request, 'pruebas.html') 


def contacto(request):
                                # este def es de la pagina de contacto
    return render(request, 'contacto.html') 

templates/Pruebas.html
{% extends 'base.html' %}

{% block contenido%}
    <h1>pruebas</h1>
{% endblock contenido %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Informatorio</title>
    <link rel="stylesheet"type="text/css" href="{% static 'css/main.css' %}">
</head>
<body class="body">
    <h1 class="titulo">Como ta server</hs1>
    <img src="{% static 'img/comotan2.webp' %}"style="width: 1200px; height: 600px;"class="centrar-imagen">
    
    <ul>
        <li><a href="{% url 'inicio' %}">Home</a></li>
        <li><a href="{% url 'contacto' %}">contacto</a>
        </li>
        <li><a href="{% url 'pruebas' %}">pruebas</a></li>
        <li><a href="{% url 'noticias:h_noticias' %}">noticias</a></li>

    </ul>

    {% block contenido %}

    {% endblock contenido %}
</body>
</html>

templates/contacto.html
{% extends 'base.html' %}

{% block contenido%}
    <h1>contacto</h1>
{% endblock contenido %}

templates/home.html
{% extends 'base.html' %}

{% block contenido%}
    <h1>Home</h1>
{% endblock contenido %}

templates/noticias/home_noticias.html
{% extends 'base.html' %}

{% block contenido%}
    <h1>Home noticias</h1>
{% endblock contenido %}